version: '3.7'

services:
  server_user:
    container_name: server_user
    build: server_user/
    ports:
      - "8300:8300"
    volumes:
      - type: bind
        source: ./server_user
        target: /code
    environment:
      - FLASK_ENV=development
  server_photo:
    container_name: server_photo
    build: server_photo/
    ports:
      - "8301:8301"
    volumes:
      - type: bind
        source: ./server_photo
        target: /code
    environment:
      - FLASK_ENV=development
  server_authentication:
    container_name: server_authentication
    build: server_authentication/
    ports:
      - "8302:8302"
    volumes:
      - type: bind
        source: ./server_authentication
        target: /code
    environment:
      - FLASK_ENV=development
  federated_gateway:
    depends_on:
     - server_user
     - server_photo
     - server_authentication
    image: xmorse/apollo-federation-gateway
    ports:
      - "4000:80"
    environment:
      URL_0: "http://server_user:8300"
      URL_1: "http://server_photo:8301"
      URL_2: "http://server_authentication:8302"
